# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account import Account  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class AccountCancelledSuccessfully(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfAccountCancelledSuccessfullyResultData=None, cancelled_account: Account=None):  # noqa: E501
        """AccountCancelledSuccessfully - a model defined in Swagger

        :param result_data: The result_data of this AccountCancelledSuccessfully.  # noqa: E501
        :type result_data: AllOfAccountCancelledSuccessfullyResultData
        :param cancelled_account: The cancelled_account of this AccountCancelledSuccessfully.  # noqa: E501
        :type cancelled_account: Account
        """
        self.swagger_types = {
            'result_data': AllOfAccountCancelledSuccessfullyResultData,
            'cancelled_account': Account
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'cancelled_account': 'cancelledAccount'
        }
        self._result_data = result_data
        self._cancelled_account = cancelled_account

    @classmethod
    def from_dict(cls, dikt) -> 'AccountCancelledSuccessfully':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountCancelledSuccessfully of this AccountCancelledSuccessfully.  # noqa: E501
        :rtype: AccountCancelledSuccessfully
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfAccountCancelledSuccessfullyResultData:
        """Gets the result_data of this AccountCancelledSuccessfully.


        :return: The result_data of this AccountCancelledSuccessfully.
        :rtype: AllOfAccountCancelledSuccessfullyResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfAccountCancelledSuccessfullyResultData):
        """Sets the result_data of this AccountCancelledSuccessfully.


        :param result_data: The result_data of this AccountCancelledSuccessfully.
        :type result_data: AllOfAccountCancelledSuccessfullyResultData
        """

        self._result_data = result_data

    @property
    def cancelled_account(self) -> Account:
        """Gets the cancelled_account of this AccountCancelledSuccessfully.


        :return: The cancelled_account of this AccountCancelledSuccessfully.
        :rtype: Account
        """
        return self._cancelled_account

    @cancelled_account.setter
    def cancelled_account(self, cancelled_account: Account):
        """Sets the cancelled_account of this AccountCancelledSuccessfully.


        :param cancelled_account: The cancelled_account of this AccountCancelledSuccessfully.
        :type cancelled_account: Account
        """

        self._cancelled_account = cancelled_account
