# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.virtual_card_descriptor import VirtualCardDescriptor  # noqa: F401,E501
from swagger_server import util


class AllOfGetVirtualCardResponseVirtual(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, v_card_id: str=None, v_pan: str=None, v_date_exp: str=None, v_cvv: str=None, v_cardholder: str=None):  # noqa: E501
        """AllOfGetVirtualCardResponseVirtual - a model defined in Swagger

        :param v_card_id: The v_card_id of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :type v_card_id: str
        :param v_pan: The v_pan of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :type v_pan: str
        :param v_date_exp: The v_date_exp of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :type v_date_exp: str
        :param v_cvv: The v_cvv of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :type v_cvv: str
        :param v_cardholder: The v_cardholder of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :type v_cardholder: str
        """
        self.swagger_types = {
            'v_card_id': str,
            'v_pan': str,
            'v_date_exp': str,
            'v_cvv': str,
            'v_cardholder': str
        }

        self.attribute_map = {
            'v_card_id': 'vCardId',
            'v_pan': 'vPan',
            'v_date_exp': 'vDateExp',
            'v_cvv': 'vCvv',
            'v_cardholder': 'vCardholder'
        }
        self._v_card_id = v_card_id
        self._v_pan = v_pan
        self._v_date_exp = v_date_exp
        self._v_cvv = v_cvv
        self._v_cardholder = v_cardholder

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfGetVirtualCardResponseVirtual':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfGetVirtualCardResponseVirtual of this AllOfGetVirtualCardResponseVirtual.  # noqa: E501
        :rtype: AllOfGetVirtualCardResponseVirtual
        """
        return util.deserialize_model(dikt, cls)

    @property
    def v_card_id(self) -> str:
        """Gets the v_card_id of this AllOfGetVirtualCardResponseVirtual.

        Identificador único do cartão virtual gerado pela paySmart  # noqa: E501

        :return: The v_card_id of this AllOfGetVirtualCardResponseVirtual.
        :rtype: str
        """
        return self._v_card_id

    @v_card_id.setter
    def v_card_id(self, v_card_id: str):
        """Sets the v_card_id of this AllOfGetVirtualCardResponseVirtual.

        Identificador único do cartão virtual gerado pela paySmart  # noqa: E501

        :param v_card_id: The v_card_id of this AllOfGetVirtualCardResponseVirtual.
        :type v_card_id: str
        """

        self._v_card_id = v_card_id

    @property
    def v_pan(self) -> str:
        """Gets the v_pan of this AllOfGetVirtualCardResponseVirtual.

        PAN do cartão virtual  # noqa: E501

        :return: The v_pan of this AllOfGetVirtualCardResponseVirtual.
        :rtype: str
        """
        return self._v_pan

    @v_pan.setter
    def v_pan(self, v_pan: str):
        """Sets the v_pan of this AllOfGetVirtualCardResponseVirtual.

        PAN do cartão virtual  # noqa: E501

        :param v_pan: The v_pan of this AllOfGetVirtualCardResponseVirtual.
        :type v_pan: str
        """

        self._v_pan = v_pan

    @property
    def v_date_exp(self) -> str:
        """Gets the v_date_exp of this AllOfGetVirtualCardResponseVirtual.

        Data de expiração do cartão virtual no formato MM/yyyy  # noqa: E501

        :return: The v_date_exp of this AllOfGetVirtualCardResponseVirtual.
        :rtype: str
        """
        return self._v_date_exp

    @v_date_exp.setter
    def v_date_exp(self, v_date_exp: str):
        """Sets the v_date_exp of this AllOfGetVirtualCardResponseVirtual.

        Data de expiração do cartão virtual no formato MM/yyyy  # noqa: E501

        :param v_date_exp: The v_date_exp of this AllOfGetVirtualCardResponseVirtual.
        :type v_date_exp: str
        """

        self._v_date_exp = v_date_exp

    @property
    def v_cvv(self) -> str:
        """Gets the v_cvv of this AllOfGetVirtualCardResponseVirtual.

        CVV do cartão virtual  # noqa: E501

        :return: The v_cvv of this AllOfGetVirtualCardResponseVirtual.
        :rtype: str
        """
        return self._v_cvv

    @v_cvv.setter
    def v_cvv(self, v_cvv: str):
        """Sets the v_cvv of this AllOfGetVirtualCardResponseVirtual.

        CVV do cartão virtual  # noqa: E501

        :param v_cvv: The v_cvv of this AllOfGetVirtualCardResponseVirtual.
        :type v_cvv: str
        """

        self._v_cvv = v_cvv

    @property
    def v_cardholder(self) -> str:
        """Gets the v_cardholder of this AllOfGetVirtualCardResponseVirtual.

        Nome do portador do cartão, para ser informado nos portais de e-commerce  # noqa: E501

        :return: The v_cardholder of this AllOfGetVirtualCardResponseVirtual.
        :rtype: str
        """
        return self._v_cardholder

    @v_cardholder.setter
    def v_cardholder(self, v_cardholder: str):
        """Sets the v_cardholder of this AllOfGetVirtualCardResponseVirtual.

        Nome do portador do cartão, para ser informado nos portais de e-commerce  # noqa: E501

        :param v_cardholder: The v_cardholder of this AllOfGetVirtualCardResponseVirtual.
        :type v_cardholder: str
        """

        self._v_cardholder = v_cardholder
