# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.installment_purchase import InstallmentPurchase  # noqa: F401,E501
from swagger_server import util


class AllInstallmentPurchase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, installment_purchases: List[InstallmentPurchase]=None):  # noqa: E501
        """AllInstallmentPurchase - a model defined in Swagger

        :param installment_purchases: The installment_purchases of this AllInstallmentPurchase.  # noqa: E501
        :type installment_purchases: List[InstallmentPurchase]
        """
        self.swagger_types = {
            'installment_purchases': List[InstallmentPurchase]
        }

        self.attribute_map = {
            'installment_purchases': 'installmentPurchases'
        }
        self._installment_purchases = installment_purchases

    @classmethod
    def from_dict(cls, dikt) -> 'AllInstallmentPurchase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllInstallmentPurchase of this AllInstallmentPurchase.  # noqa: E501
        :rtype: AllInstallmentPurchase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def installment_purchases(self) -> List[InstallmentPurchase]:
        """Gets the installment_purchases of this AllInstallmentPurchase.


        :return: The installment_purchases of this AllInstallmentPurchase.
        :rtype: List[InstallmentPurchase]
        """
        return self._installment_purchases

    @installment_purchases.setter
    def installment_purchases(self, installment_purchases: List[InstallmentPurchase]):
        """Sets the installment_purchases of this AllInstallmentPurchase.


        :param installment_purchases: The installment_purchases of this AllInstallmentPurchase.
        :type installment_purchases: List[InstallmentPurchase]
        """

        self._installment_purchases = installment_purchases
