# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bank_account_info import BankAccountInfo  # noqa: F401,E501
from swagger_server import util


class AllOfNewAccountRequestBankAccount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bank_id: str=None, bank_name: str=None, agency_code: int=None, account_number: int=None):  # noqa: E501
        """AllOfNewAccountRequestBankAccount - a model defined in Swagger

        :param bank_id: The bank_id of this AllOfNewAccountRequestBankAccount.  # noqa: E501
        :type bank_id: str
        :param bank_name: The bank_name of this AllOfNewAccountRequestBankAccount.  # noqa: E501
        :type bank_name: str
        :param agency_code: The agency_code of this AllOfNewAccountRequestBankAccount.  # noqa: E501
        :type agency_code: int
        :param account_number: The account_number of this AllOfNewAccountRequestBankAccount.  # noqa: E501
        :type account_number: int
        """
        self.swagger_types = {
            'bank_id': str,
            'bank_name': str,
            'agency_code': int,
            'account_number': int
        }

        self.attribute_map = {
            'bank_id': 'bankID',
            'bank_name': 'bankName',
            'agency_code': 'agencyCode',
            'account_number': 'accountNumber'
        }
        self._bank_id = bank_id
        self._bank_name = bank_name
        self._agency_code = agency_code
        self._account_number = account_number

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfNewAccountRequestBankAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfNewAccountRequestBankAccount of this AllOfNewAccountRequestBankAccount.  # noqa: E501
        :rtype: AllOfNewAccountRequestBankAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bank_id(self) -> str:
        """Gets the bank_id of this AllOfNewAccountRequestBankAccount.

        Identificador do Banco. No Brasil usar número do Banco.  # noqa: E501

        :return: The bank_id of this AllOfNewAccountRequestBankAccount.
        :rtype: str
        """
        return self._bank_id

    @bank_id.setter
    def bank_id(self, bank_id: str):
        """Sets the bank_id of this AllOfNewAccountRequestBankAccount.

        Identificador do Banco. No Brasil usar número do Banco.  # noqa: E501

        :param bank_id: The bank_id of this AllOfNewAccountRequestBankAccount.
        :type bank_id: str
        """

        self._bank_id = bank_id

    @property
    def bank_name(self) -> str:
        """Gets the bank_name of this AllOfNewAccountRequestBankAccount.

        Nome do banco.  # noqa: E501

        :return: The bank_name of this AllOfNewAccountRequestBankAccount.
        :rtype: str
        """
        return self._bank_name

    @bank_name.setter
    def bank_name(self, bank_name: str):
        """Sets the bank_name of this AllOfNewAccountRequestBankAccount.

        Nome do banco.  # noqa: E501

        :param bank_name: The bank_name of this AllOfNewAccountRequestBankAccount.
        :type bank_name: str
        """

        self._bank_name = bank_name

    @property
    def agency_code(self) -> int:
        """Gets the agency_code of this AllOfNewAccountRequestBankAccount.

        Código da agência.  # noqa: E501

        :return: The agency_code of this AllOfNewAccountRequestBankAccount.
        :rtype: int
        """
        return self._agency_code

    @agency_code.setter
    def agency_code(self, agency_code: int):
        """Sets the agency_code of this AllOfNewAccountRequestBankAccount.

        Código da agência.  # noqa: E501

        :param agency_code: The agency_code of this AllOfNewAccountRequestBankAccount.
        :type agency_code: int
        """

        self._agency_code = agency_code

    @property
    def account_number(self) -> int:
        """Gets the account_number of this AllOfNewAccountRequestBankAccount.

        Número da conta, incluindo dígito verificador.  # noqa: E501

        :return: The account_number of this AllOfNewAccountRequestBankAccount.
        :rtype: int
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number: int):
        """Sets the account_number of this AllOfNewAccountRequestBankAccount.

        Número da conta, incluindo dígito verificador.  # noqa: E501

        :param account_number: The account_number of this AllOfNewAccountRequestBankAccount.
        :type account_number: int
        """

        self._account_number = account_number
