# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.virtual_card_info import VirtualCardInfo  # noqa: F401,E501
from swagger_server import util


class AllOfComposedVirtualCardInfoInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status_code: str=None, card_id: str=None, status_description: str=None):  # noqa: E501
        """AllOfComposedVirtualCardInfoInfo - a model defined in Swagger

        :param status_code: The status_code of this AllOfComposedVirtualCardInfoInfo.  # noqa: E501
        :type status_code: str
        :param card_id: The card_id of this AllOfComposedVirtualCardInfoInfo.  # noqa: E501
        :type card_id: str
        :param status_description: The status_description of this AllOfComposedVirtualCardInfoInfo.  # noqa: E501
        :type status_description: str
        """
        self.swagger_types = {
            'status_code': str,
            'card_id': str,
            'status_description': str
        }

        self.attribute_map = {
            'status_code': 'statusCode',
            'card_id': 'cardId',
            'status_description': 'statusDescription'
        }
        self._status_code = status_code
        self._card_id = card_id
        self._status_description = status_description

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfComposedVirtualCardInfoInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfComposedVirtualCardInfoInfo of this AllOfComposedVirtualCardInfoInfo.  # noqa: E501
        :rtype: AllOfComposedVirtualCardInfoInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status_code(self) -> str:
        """Gets the status_code of this AllOfComposedVirtualCardInfoInfo.

        Status do cartão virtual  # noqa: E501

        :return: The status_code of this AllOfComposedVirtualCardInfoInfo.
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: str):
        """Sets the status_code of this AllOfComposedVirtualCardInfoInfo.

        Status do cartão virtual  # noqa: E501

        :param status_code: The status_code of this AllOfComposedVirtualCardInfoInfo.
        :type status_code: str
        """

        self._status_code = status_code

    @property
    def card_id(self) -> str:
        """Gets the card_id of this AllOfComposedVirtualCardInfoInfo.

        Identificador do cartão real associado ao cartão virtual  # noqa: E501

        :return: The card_id of this AllOfComposedVirtualCardInfoInfo.
        :rtype: str
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id: str):
        """Sets the card_id of this AllOfComposedVirtualCardInfoInfo.

        Identificador do cartão real associado ao cartão virtual  # noqa: E501

        :param card_id: The card_id of this AllOfComposedVirtualCardInfoInfo.
        :type card_id: str
        """

        self._card_id = card_id

    @property
    def status_description(self) -> str:
        """Gets the status_description of this AllOfComposedVirtualCardInfoInfo.

        Descrição do status do cartão virtual  # noqa: E501

        :return: The status_description of this AllOfComposedVirtualCardInfoInfo.
        :rtype: str
        """
        return self._status_description

    @status_description.setter
    def status_description(self, status_description: str):
        """Sets the status_description of this AllOfComposedVirtualCardInfoInfo.

        Descrição do status do cartão virtual  # noqa: E501

        :param status_description: The status_description of this AllOfComposedVirtualCardInfoInfo.
        :type status_description: str
        """

        self._status_description = status_description
