# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.amount import Amount  # noqa: F401,E501
from swagger_server import util


class Balance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, current_balance: Amount=None):  # noqa: E501
        """Balance - a model defined in Swagger

        :param current_balance: The current_balance of this Balance.  # noqa: E501
        :type current_balance: Amount
        """
        self.swagger_types = {
            'current_balance': Amount
        }

        self.attribute_map = {
            'current_balance': 'currentBalance'
        }
        self._current_balance = current_balance

    @classmethod
    def from_dict(cls, dikt) -> 'Balance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Balance of this Balance.  # noqa: E501
        :rtype: Balance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_balance(self) -> Amount:
        """Gets the current_balance of this Balance.


        :return: The current_balance of this Balance.
        :rtype: Amount
        """
        return self._current_balance

    @current_balance.setter
    def current_balance(self, current_balance: Amount):
        """Sets the current_balance of this Balance.


        :param current_balance: The current_balance of this Balance.
        :type current_balance: Amount
        """

        self._current_balance = current_balance
