# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.composed_virtual_card_info import ComposedVirtualCardInfo  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CancelVirtualCardResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfCancelVirtualCardResponseResultData=None, cancelled_virtual_card: ComposedVirtualCardInfo=None):  # noqa: E501
        """CancelVirtualCardResponse - a model defined in Swagger

        :param result_data: The result_data of this CancelVirtualCardResponse.  # noqa: E501
        :type result_data: AllOfCancelVirtualCardResponseResultData
        :param cancelled_virtual_card: The cancelled_virtual_card of this CancelVirtualCardResponse.  # noqa: E501
        :type cancelled_virtual_card: ComposedVirtualCardInfo
        """
        self.swagger_types = {
            'result_data': AllOfCancelVirtualCardResponseResultData,
            'cancelled_virtual_card': ComposedVirtualCardInfo
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'cancelled_virtual_card': 'cancelledVirtualCard'
        }
        self._result_data = result_data
        self._cancelled_virtual_card = cancelled_virtual_card

    @classmethod
    def from_dict(cls, dikt) -> 'CancelVirtualCardResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CancelVirtualCardResponse of this CancelVirtualCardResponse.  # noqa: E501
        :rtype: CancelVirtualCardResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfCancelVirtualCardResponseResultData:
        """Gets the result_data of this CancelVirtualCardResponse.


        :return: The result_data of this CancelVirtualCardResponse.
        :rtype: AllOfCancelVirtualCardResponseResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfCancelVirtualCardResponseResultData):
        """Sets the result_data of this CancelVirtualCardResponse.


        :param result_data: The result_data of this CancelVirtualCardResponse.
        :type result_data: AllOfCancelVirtualCardResponseResultData
        """

        self._result_data = result_data

    @property
    def cancelled_virtual_card(self) -> ComposedVirtualCardInfo:
        """Gets the cancelled_virtual_card of this CancelVirtualCardResponse.


        :return: The cancelled_virtual_card of this CancelVirtualCardResponse.
        :rtype: ComposedVirtualCardInfo
        """
        return self._cancelled_virtual_card

    @cancelled_virtual_card.setter
    def cancelled_virtual_card(self, cancelled_virtual_card: ComposedVirtualCardInfo):
        """Sets the cancelled_virtual_card of this CancelVirtualCardResponse.


        :param cancelled_virtual_card: The cancelled_virtual_card of this CancelVirtualCardResponse.
        :type cancelled_virtual_card: ComposedVirtualCardInfo
        """

        self._cancelled_virtual_card = cancelled_virtual_card
