# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_audit import SourceAudit  # noqa: F401,E501
from swagger_server import util


class CancelAccountRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cancellation_code: int=None, reason: str=None, source_audit: SourceAudit=None):  # noqa: E501
        """CancelAccountRequest - a model defined in Swagger

        :param cancellation_code: The cancellation_code of this CancelAccountRequest.  # noqa: E501
        :type cancellation_code: int
        :param reason: The reason of this CancelAccountRequest.  # noqa: E501
        :type reason: str
        :param source_audit: The source_audit of this CancelAccountRequest.  # noqa: E501
        :type source_audit: SourceAudit
        """
        self.swagger_types = {
            'cancellation_code': int,
            'reason': str,
            'source_audit': SourceAudit
        }

        self.attribute_map = {
            'cancellation_code': 'cancellationCode',
            'reason': 'reason',
            'source_audit': 'sourceAudit'
        }
        self._cancellation_code = cancellation_code
        self._reason = reason
        self._source_audit = source_audit

    @classmethod
    def from_dict(cls, dikt) -> 'CancelAccountRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CancelAccountRequest of this CancelAccountRequest.  # noqa: E501
        :rtype: CancelAccountRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cancellation_code(self) -> int:
        """Gets the cancellation_code of this CancelAccountRequest.

        Código identificando o tipo de cancelamento.  # noqa: E501

        :return: The cancellation_code of this CancelAccountRequest.
        :rtype: int
        """
        return self._cancellation_code

    @cancellation_code.setter
    def cancellation_code(self, cancellation_code: int):
        """Sets the cancellation_code of this CancelAccountRequest.

        Código identificando o tipo de cancelamento.  # noqa: E501

        :param cancellation_code: The cancellation_code of this CancelAccountRequest.
        :type cancellation_code: int
        """
        if cancellation_code is None:
            raise ValueError("Invalid value for `cancellation_code`, must not be `None`")  # noqa: E501

        self._cancellation_code = cancellation_code

    @property
    def reason(self) -> str:
        """Gets the reason of this CancelAccountRequest.

        Motivo do cancelamento.  # noqa: E501

        :return: The reason of this CancelAccountRequest.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this CancelAccountRequest.

        Motivo do cancelamento.  # noqa: E501

        :param reason: The reason of this CancelAccountRequest.
        :type reason: str
        """

        self._reason = reason

    @property
    def source_audit(self) -> SourceAudit:
        """Gets the source_audit of this CancelAccountRequest.


        :return: The source_audit of this CancelAccountRequest.
        :rtype: SourceAudit
        """
        return self._source_audit

    @source_audit.setter
    def source_audit(self, source_audit: SourceAudit):
        """Sets the source_audit of this CancelAccountRequest.


        :param source_audit: The source_audit of this CancelAccountRequest.
        :type source_audit: SourceAudit
        """

        self._source_audit = source_audit
