# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cardholder_data import CardholderData  # noqa: F401,E501
from swagger_server import util


class Cardholder(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cardholder_id: str=None, cardholder_data: CardholderData=None):  # noqa: E501
        """Cardholder - a model defined in Swagger

        :param cardholder_id: The cardholder_id of this Cardholder.  # noqa: E501
        :type cardholder_id: str
        :param cardholder_data: The cardholder_data of this Cardholder.  # noqa: E501
        :type cardholder_data: CardholderData
        """
        self.swagger_types = {
            'cardholder_id': str,
            'cardholder_data': CardholderData
        }

        self.attribute_map = {
            'cardholder_id': 'cardholderId',
            'cardholder_data': 'cardholderData'
        }
        self._cardholder_id = cardholder_id
        self._cardholder_data = cardholder_data

    @classmethod
    def from_dict(cls, dikt) -> 'Cardholder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cardholder of this Cardholder.  # noqa: E501
        :rtype: Cardholder
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cardholder_id(self) -> str:
        """Gets the cardholder_id of this Cardholder.

        Identificador único do portador.  # noqa: E501

        :return: The cardholder_id of this Cardholder.
        :rtype: str
        """
        return self._cardholder_id

    @cardholder_id.setter
    def cardholder_id(self, cardholder_id: str):
        """Sets the cardholder_id of this Cardholder.

        Identificador único do portador.  # noqa: E501

        :param cardholder_id: The cardholder_id of this Cardholder.
        :type cardholder_id: str
        """

        self._cardholder_id = cardholder_id

    @property
    def cardholder_data(self) -> CardholderData:
        """Gets the cardholder_data of this Cardholder.


        :return: The cardholder_data of this Cardholder.
        :rtype: CardholderData
        """
        return self._cardholder_data

    @cardholder_data.setter
    def cardholder_data(self, cardholder_data: CardholderData):
        """Sets the cardholder_data of this Cardholder.


        :param cardholder_data: The cardholder_data of this Cardholder.
        :type cardholder_data: CardholderData
        """

        self._cardholder_data = cardholder_data
