# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_audit import SourceAudit  # noqa: F401,E501
from swagger_server import util


class CardReissueRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, issuer_card_id: str=None, extra_data: str=None, issuer_card_reissue_id: str=None, reason: str=None, source_audit: SourceAudit=None):  # noqa: E501
        """CardReissueRequest - a model defined in Swagger

        :param issuer_card_id: The issuer_card_id of this CardReissueRequest.  # noqa: E501
        :type issuer_card_id: str
        :param extra_data: The extra_data of this CardReissueRequest.  # noqa: E501
        :type extra_data: str
        :param issuer_card_reissue_id: The issuer_card_reissue_id of this CardReissueRequest.  # noqa: E501
        :type issuer_card_reissue_id: str
        :param reason: The reason of this CardReissueRequest.  # noqa: E501
        :type reason: str
        :param source_audit: The source_audit of this CardReissueRequest.  # noqa: E501
        :type source_audit: SourceAudit
        """
        self.swagger_types = {
            'issuer_card_id': str,
            'extra_data': str,
            'issuer_card_reissue_id': str,
            'reason': str,
            'source_audit': SourceAudit
        }

        self.attribute_map = {
            'issuer_card_id': 'issuerCardId',
            'extra_data': 'extraData',
            'issuer_card_reissue_id': 'issuerCardReissueId',
            'reason': 'reason',
            'source_audit': 'sourceAudit'
        }
        self._issuer_card_id = issuer_card_id
        self._extra_data = extra_data
        self._issuer_card_reissue_id = issuer_card_reissue_id
        self._reason = reason
        self._source_audit = source_audit

    @classmethod
    def from_dict(cls, dikt) -> 'CardReissueRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CardReissueRequest of this CardReissueRequest.  # noqa: E501
        :rtype: CardReissueRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issuer_card_id(self) -> str:
        """Gets the issuer_card_id of this CardReissueRequest.

        Identificador do novo cartão no emissor  # noqa: E501

        :return: The issuer_card_id of this CardReissueRequest.
        :rtype: str
        """
        return self._issuer_card_id

    @issuer_card_id.setter
    def issuer_card_id(self, issuer_card_id: str):
        """Sets the issuer_card_id of this CardReissueRequest.

        Identificador do novo cartão no emissor  # noqa: E501

        :param issuer_card_id: The issuer_card_id of this CardReissueRequest.
        :type issuer_card_id: str
        """

        self._issuer_card_id = issuer_card_id

    @property
    def extra_data(self) -> str:
        """Gets the extra_data of this CardReissueRequest.

        Dados extras para o novo cartão  # noqa: E501

        :return: The extra_data of this CardReissueRequest.
        :rtype: str
        """
        return self._extra_data

    @extra_data.setter
    def extra_data(self, extra_data: str):
        """Sets the extra_data of this CardReissueRequest.

        Dados extras para o novo cartão  # noqa: E501

        :param extra_data: The extra_data of this CardReissueRequest.
        :type extra_data: str
        """

        self._extra_data = extra_data

    @property
    def issuer_card_reissue_id(self) -> str:
        """Gets the issuer_card_reissue_id of this CardReissueRequest.

        Identificador único da requisição de nova via. Gerado pelo emissor.  # noqa: E501

        :return: The issuer_card_reissue_id of this CardReissueRequest.
        :rtype: str
        """
        return self._issuer_card_reissue_id

    @issuer_card_reissue_id.setter
    def issuer_card_reissue_id(self, issuer_card_reissue_id: str):
        """Sets the issuer_card_reissue_id of this CardReissueRequest.

        Identificador único da requisição de nova via. Gerado pelo emissor.  # noqa: E501

        :param issuer_card_reissue_id: The issuer_card_reissue_id of this CardReissueRequest.
        :type issuer_card_reissue_id: str
        """

        self._issuer_card_reissue_id = issuer_card_reissue_id

    @property
    def reason(self) -> str:
        """Gets the reason of this CardReissueRequest.

        Motivo da nova via.  # noqa: E501

        :return: The reason of this CardReissueRequest.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this CardReissueRequest.

        Motivo da nova via.  # noqa: E501

        :param reason: The reason of this CardReissueRequest.
        :type reason: str
        """

        self._reason = reason

    @property
    def source_audit(self) -> SourceAudit:
        """Gets the source_audit of this CardReissueRequest.


        :return: The source_audit of this CardReissueRequest.
        :rtype: SourceAudit
        """
        return self._source_audit

    @source_audit.setter
    def source_audit(self, source_audit: SourceAudit):
        """Sets the source_audit of this CardReissueRequest.


        :param source_audit: The source_audit of this CardReissueRequest.
        :type source_audit: SourceAudit
        """

        self._source_audit = source_audit
