# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class ComposedVirtualCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, virtual: AllOfComposedVirtualCardInfoVirtual=None, constraints: AllOfComposedVirtualCardInfoConstraints=None, info: AllOfComposedVirtualCardInfoInfo=None):  # noqa: E501
        """ComposedVirtualCardInfo - a model defined in Swagger

        :param virtual: The virtual of this ComposedVirtualCardInfo.  # noqa: E501
        :type virtual: AllOfComposedVirtualCardInfoVirtual
        :param constraints: The constraints of this ComposedVirtualCardInfo.  # noqa: E501
        :type constraints: AllOfComposedVirtualCardInfoConstraints
        :param info: The info of this ComposedVirtualCardInfo.  # noqa: E501
        :type info: AllOfComposedVirtualCardInfoInfo
        """
        self.swagger_types = {
            'virtual': AllOfComposedVirtualCardInfoVirtual,
            'constraints': AllOfComposedVirtualCardInfoConstraints,
            'info': AllOfComposedVirtualCardInfoInfo
        }

        self.attribute_map = {
            'virtual': 'virtual',
            'constraints': 'constraints',
            'info': 'info'
        }
        self._virtual = virtual
        self._constraints = constraints
        self._info = info

    @classmethod
    def from_dict(cls, dikt) -> 'ComposedVirtualCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ComposedVirtualCardInfo of this ComposedVirtualCardInfo.  # noqa: E501
        :rtype: ComposedVirtualCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def virtual(self) -> AllOfComposedVirtualCardInfoVirtual:
        """Gets the virtual of this ComposedVirtualCardInfo.


        :return: The virtual of this ComposedVirtualCardInfo.
        :rtype: AllOfComposedVirtualCardInfoVirtual
        """
        return self._virtual

    @virtual.setter
    def virtual(self, virtual: AllOfComposedVirtualCardInfoVirtual):
        """Sets the virtual of this ComposedVirtualCardInfo.


        :param virtual: The virtual of this ComposedVirtualCardInfo.
        :type virtual: AllOfComposedVirtualCardInfoVirtual
        """

        self._virtual = virtual

    @property
    def constraints(self) -> AllOfComposedVirtualCardInfoConstraints:
        """Gets the constraints of this ComposedVirtualCardInfo.


        :return: The constraints of this ComposedVirtualCardInfo.
        :rtype: AllOfComposedVirtualCardInfoConstraints
        """
        return self._constraints

    @constraints.setter
    def constraints(self, constraints: AllOfComposedVirtualCardInfoConstraints):
        """Sets the constraints of this ComposedVirtualCardInfo.


        :param constraints: The constraints of this ComposedVirtualCardInfo.
        :type constraints: AllOfComposedVirtualCardInfoConstraints
        """

        self._constraints = constraints

    @property
    def info(self) -> AllOfComposedVirtualCardInfoInfo:
        """Gets the info of this ComposedVirtualCardInfo.


        :return: The info of this ComposedVirtualCardInfo.
        :rtype: AllOfComposedVirtualCardInfoInfo
        """
        return self._info

    @info.setter
    def info(self, info: AllOfComposedVirtualCardInfoInfo):
        """Sets the info of this ComposedVirtualCardInfo.


        :param info: The info of this ComposedVirtualCardInfo.
        :type info: AllOfComposedVirtualCardInfoInfo
        """

        self._info = info
