# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CreateVirtualCardResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfCreateVirtualCardResponseResultData=None, virtual_card: AllOfCreateVirtualCardResponseVirtualCard=None):  # noqa: E501
        """CreateVirtualCardResponse - a model defined in Swagger

        :param result_data: The result_data of this CreateVirtualCardResponse.  # noqa: E501
        :type result_data: AllOfCreateVirtualCardResponseResultData
        :param virtual_card: The virtual_card of this CreateVirtualCardResponse.  # noqa: E501
        :type virtual_card: AllOfCreateVirtualCardResponseVirtualCard
        """
        self.swagger_types = {
            'result_data': AllOfCreateVirtualCardResponseResultData,
            'virtual_card': AllOfCreateVirtualCardResponseVirtualCard
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'virtual_card': 'virtualCard'
        }
        self._result_data = result_data
        self._virtual_card = virtual_card

    @classmethod
    def from_dict(cls, dikt) -> 'CreateVirtualCardResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateVirtualCardResponse of this CreateVirtualCardResponse.  # noqa: E501
        :rtype: CreateVirtualCardResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfCreateVirtualCardResponseResultData:
        """Gets the result_data of this CreateVirtualCardResponse.


        :return: The result_data of this CreateVirtualCardResponse.
        :rtype: AllOfCreateVirtualCardResponseResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfCreateVirtualCardResponseResultData):
        """Sets the result_data of this CreateVirtualCardResponse.


        :param result_data: The result_data of this CreateVirtualCardResponse.
        :type result_data: AllOfCreateVirtualCardResponseResultData
        """

        self._result_data = result_data

    @property
    def virtual_card(self) -> AllOfCreateVirtualCardResponseVirtualCard:
        """Gets the virtual_card of this CreateVirtualCardResponse.


        :return: The virtual_card of this CreateVirtualCardResponse.
        :rtype: AllOfCreateVirtualCardResponseVirtualCard
        """
        return self._virtual_card

    @virtual_card.setter
    def virtual_card(self, virtual_card: AllOfCreateVirtualCardResponseVirtualCard):
        """Sets the virtual_card of this CreateVirtualCardResponse.


        :param virtual_card: The virtual_card of this CreateVirtualCardResponse.
        :type virtual_card: AllOfCreateVirtualCardResponseVirtualCard
        """

        self._virtual_card = virtual_card
