# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CreditInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, credit_limit: AllOfCreditInfoCreditLimit=None, payment_due: int=None):  # noqa: E501
        """CreditInfo - a model defined in Swagger

        :param credit_limit: The credit_limit of this CreditInfo.  # noqa: E501
        :type credit_limit: AllOfCreditInfoCreditLimit
        :param payment_due: The payment_due of this CreditInfo.  # noqa: E501
        :type payment_due: int
        """
        self.swagger_types = {
            'credit_limit': AllOfCreditInfoCreditLimit,
            'payment_due': int
        }

        self.attribute_map = {
            'credit_limit': 'creditLimit',
            'payment_due': 'paymentDue'
        }
        self._credit_limit = credit_limit
        self._payment_due = payment_due

    @classmethod
    def from_dict(cls, dikt) -> 'CreditInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreditInfo of this CreditInfo.  # noqa: E501
        :rtype: CreditInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def credit_limit(self) -> AllOfCreditInfoCreditLimit:
        """Gets the credit_limit of this CreditInfo.

        Para produtos de crédito pós-pago: Valor limite de crédito atribuído à conta pelo emissor.  # noqa: E501

        :return: The credit_limit of this CreditInfo.
        :rtype: AllOfCreditInfoCreditLimit
        """
        return self._credit_limit

    @credit_limit.setter
    def credit_limit(self, credit_limit: AllOfCreditInfoCreditLimit):
        """Sets the credit_limit of this CreditInfo.

        Para produtos de crédito pós-pago: Valor limite de crédito atribuído à conta pelo emissor.  # noqa: E501

        :param credit_limit: The credit_limit of this CreditInfo.
        :type credit_limit: AllOfCreditInfoCreditLimit
        """

        self._credit_limit = credit_limit

    @property
    def payment_due(self) -> int:
        """Gets the payment_due of this CreditInfo.

        Para produtos de crédito pós-pago: Dia de vencimento da fatura mensal.  # noqa: E501

        :return: The payment_due of this CreditInfo.
        :rtype: int
        """
        return self._payment_due

    @payment_due.setter
    def payment_due(self, payment_due: int):
        """Sets the payment_due of this CreditInfo.

        Para produtos de crédito pós-pago: Dia de vencimento da fatura mensal.  # noqa: E501

        :param payment_due: The payment_due of this CreditInfo.
        :type payment_due: int
        """

        self._payment_due = payment_due
