# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_audit import SourceAudit  # noqa: F401,E501
from swagger_server import util


class DisputeReversalRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, issuer_dispute_reversal_id: str=None, text_message: str=None, source_audit: SourceAudit=None):  # noqa: E501
        """DisputeReversalRequest - a model defined in Swagger

        :param issuer_dispute_reversal_id: The issuer_dispute_reversal_id of this DisputeReversalRequest.  # noqa: E501
        :type issuer_dispute_reversal_id: str
        :param text_message: The text_message of this DisputeReversalRequest.  # noqa: E501
        :type text_message: str
        :param source_audit: The source_audit of this DisputeReversalRequest.  # noqa: E501
        :type source_audit: SourceAudit
        """
        self.swagger_types = {
            'issuer_dispute_reversal_id': str,
            'text_message': str,
            'source_audit': SourceAudit
        }

        self.attribute_map = {
            'issuer_dispute_reversal_id': 'issuerDisputeReversalId',
            'text_message': 'textMessage',
            'source_audit': 'sourceAudit'
        }
        self._issuer_dispute_reversal_id = issuer_dispute_reversal_id
        self._text_message = text_message
        self._source_audit = source_audit

    @classmethod
    def from_dict(cls, dikt) -> 'DisputeReversalRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DisputeReversalRequest of this DisputeReversalRequest.  # noqa: E501
        :rtype: DisputeReversalRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issuer_dispute_reversal_id(self) -> str:
        """Gets the issuer_dispute_reversal_id of this DisputeReversalRequest.

        Identificador único do pedido de desistência da disputa. Gerado pelo emissor.  # noqa: E501

        :return: The issuer_dispute_reversal_id of this DisputeReversalRequest.
        :rtype: str
        """
        return self._issuer_dispute_reversal_id

    @issuer_dispute_reversal_id.setter
    def issuer_dispute_reversal_id(self, issuer_dispute_reversal_id: str):
        """Sets the issuer_dispute_reversal_id of this DisputeReversalRequest.

        Identificador único do pedido de desistência da disputa. Gerado pelo emissor.  # noqa: E501

        :param issuer_dispute_reversal_id: The issuer_dispute_reversal_id of this DisputeReversalRequest.
        :type issuer_dispute_reversal_id: str
        """

        self._issuer_dispute_reversal_id = issuer_dispute_reversal_id

    @property
    def text_message(self) -> str:
        """Gets the text_message of this DisputeReversalRequest.

        Mensagem de texto justificando o motivo da desistência da disputa (opcional).  # noqa: E501

        :return: The text_message of this DisputeReversalRequest.
        :rtype: str
        """
        return self._text_message

    @text_message.setter
    def text_message(self, text_message: str):
        """Sets the text_message of this DisputeReversalRequest.

        Mensagem de texto justificando o motivo da desistência da disputa (opcional).  # noqa: E501

        :param text_message: The text_message of this DisputeReversalRequest.
        :type text_message: str
        """

        self._text_message = text_message

    @property
    def source_audit(self) -> SourceAudit:
        """Gets the source_audit of this DisputeReversalRequest.


        :return: The source_audit of this DisputeReversalRequest.
        :rtype: SourceAudit
        """
        return self._source_audit

    @source_audit.setter
    def source_audit(self, source_audit: SourceAudit):
        """Sets the source_audit of this DisputeReversalRequest.


        :param source_audit: The source_audit of this DisputeReversalRequest.
        :type source_audit: SourceAudit
        """

        self._source_audit = source_audit
