# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DisputeStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WAITING_FOR_RESPONSE_FROM_ISSUER = "waiting_for_response_from_issuer"
    WAITING_FOR_RESPONSE_FROM_ACQUIRER = "waiting_for_response_from_acquirer"
    WAITING_FOR_RESPONSE_FROM_BRAND = "waiting_for_response_from_brand"
    ACCEPTED = "accepted"
    DENIED = "denied"
    ISSUER_WON = "issuer_won"
    ISSUER_LOST = "issuer_lost"
    CANCELED_BY_ISSUER = "canceled_by_issuer"
    def __init__(self):  # noqa: E501
        """DisputeStatus - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DisputeStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DisputeStatus of this DisputeStatus.  # noqa: E501
        :rtype: DisputeStatus
        """
        return util.deserialize_model(dikt, cls)
