# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dispute import Dispute  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class DisputeCreatedSuccessfully(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfDisputeCreatedSuccessfullyResultData=None, dispute: Dispute=None):  # noqa: E501
        """DisputeCreatedSuccessfully - a model defined in Swagger

        :param result_data: The result_data of this DisputeCreatedSuccessfully.  # noqa: E501
        :type result_data: AllOfDisputeCreatedSuccessfullyResultData
        :param dispute: The dispute of this DisputeCreatedSuccessfully.  # noqa: E501
        :type dispute: Dispute
        """
        self.swagger_types = {
            'result_data': AllOfDisputeCreatedSuccessfullyResultData,
            'dispute': Dispute
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'dispute': 'dispute'
        }
        self._result_data = result_data
        self._dispute = dispute

    @classmethod
    def from_dict(cls, dikt) -> 'DisputeCreatedSuccessfully':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DisputeCreatedSuccessfully of this DisputeCreatedSuccessfully.  # noqa: E501
        :rtype: DisputeCreatedSuccessfully
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfDisputeCreatedSuccessfullyResultData:
        """Gets the result_data of this DisputeCreatedSuccessfully.


        :return: The result_data of this DisputeCreatedSuccessfully.
        :rtype: AllOfDisputeCreatedSuccessfullyResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfDisputeCreatedSuccessfullyResultData):
        """Sets the result_data of this DisputeCreatedSuccessfully.


        :param result_data: The result_data of this DisputeCreatedSuccessfully.
        :type result_data: AllOfDisputeCreatedSuccessfullyResultData
        """

        self._result_data = result_data

    @property
    def dispute(self) -> Dispute:
        """Gets the dispute of this DisputeCreatedSuccessfully.


        :return: The dispute of this DisputeCreatedSuccessfully.
        :rtype: Dispute
        """
        return self._dispute

    @dispute.setter
    def dispute(self, dispute: Dispute):
        """Sets the dispute of this DisputeCreatedSuccessfully.


        :param dispute: The dispute of this DisputeCreatedSuccessfully.
        :type dispute: Dispute
        """

        self._dispute = dispute
