# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.future_statement import FutureStatement  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class FutureStatementList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfFutureStatementListResultData=None, statement_list: List[FutureStatement]=None):  # noqa: E501
        """FutureStatementList - a model defined in Swagger

        :param result_data: The result_data of this FutureStatementList.  # noqa: E501
        :type result_data: AllOfFutureStatementListResultData
        :param statement_list: The statement_list of this FutureStatementList.  # noqa: E501
        :type statement_list: List[FutureStatement]
        """
        self.swagger_types = {
            'result_data': AllOfFutureStatementListResultData,
            'statement_list': List[FutureStatement]
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'statement_list': 'statementList'
        }
        self._result_data = result_data
        self._statement_list = statement_list

    @classmethod
    def from_dict(cls, dikt) -> 'FutureStatementList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FutureStatementList of this FutureStatementList.  # noqa: E501
        :rtype: FutureStatementList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfFutureStatementListResultData:
        """Gets the result_data of this FutureStatementList.


        :return: The result_data of this FutureStatementList.
        :rtype: AllOfFutureStatementListResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfFutureStatementListResultData):
        """Sets the result_data of this FutureStatementList.


        :param result_data: The result_data of this FutureStatementList.
        :type result_data: AllOfFutureStatementListResultData
        """

        self._result_data = result_data

    @property
    def statement_list(self) -> List[FutureStatement]:
        """Gets the statement_list of this FutureStatementList.

        Lista de faturas futuras.  # noqa: E501

        :return: The statement_list of this FutureStatementList.
        :rtype: List[FutureStatement]
        """
        return self._statement_list

    @statement_list.setter
    def statement_list(self, statement_list: List[FutureStatement]):
        """Sets the statement_list of this FutureStatementList.

        Lista de faturas futuras.  # noqa: E501

        :param statement_list: The statement_list of this FutureStatementList.
        :type statement_list: List[FutureStatement]
        """

        self._statement_list = statement_list
