# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server.models.source_audit import SourceAudit  # noqa: F401,E501
from swagger_server import util


class NewCreditRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, issuer_request_id: str=None, inclusion_date: datetime=None, amount: AllOfNewCreditRequestAmount=None, credit_type: int=None, source_audit: SourceAudit=None):  # noqa: E501
        """NewCreditRequest - a model defined in Swagger

        :param issuer_request_id: The issuer_request_id of this NewCreditRequest.  # noqa: E501
        :type issuer_request_id: str
        :param inclusion_date: The inclusion_date of this NewCreditRequest.  # noqa: E501
        :type inclusion_date: datetime
        :param amount: The amount of this NewCreditRequest.  # noqa: E501
        :type amount: AllOfNewCreditRequestAmount
        :param credit_type: The credit_type of this NewCreditRequest.  # noqa: E501
        :type credit_type: int
        :param source_audit: The source_audit of this NewCreditRequest.  # noqa: E501
        :type source_audit: SourceAudit
        """
        self.swagger_types = {
            'issuer_request_id': str,
            'inclusion_date': datetime,
            'amount': AllOfNewCreditRequestAmount,
            'credit_type': int,
            'source_audit': SourceAudit
        }

        self.attribute_map = {
            'issuer_request_id': 'issuerRequestId',
            'inclusion_date': 'inclusion_date',
            'amount': 'amount',
            'credit_type': 'credit_type',
            'source_audit': 'sourceAudit'
        }
        self._issuer_request_id = issuer_request_id
        self._inclusion_date = inclusion_date
        self._amount = amount
        self._credit_type = credit_type
        self._source_audit = source_audit

    @classmethod
    def from_dict(cls, dikt) -> 'NewCreditRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewCreditRequest of this NewCreditRequest.  # noqa: E501
        :rtype: NewCreditRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issuer_request_id(self) -> str:
        """Gets the issuer_request_id of this NewCreditRequest.

        Identificador único da requisição gerado pelo emissor. Esse identificador é ecoado na resposta. Nenhuma verificação dele é feita por parte da paySmart, o emissor é livre para escolher o valor que quiser.  # noqa: E501

        :return: The issuer_request_id of this NewCreditRequest.
        :rtype: str
        """
        return self._issuer_request_id

    @issuer_request_id.setter
    def issuer_request_id(self, issuer_request_id: str):
        """Sets the issuer_request_id of this NewCreditRequest.

        Identificador único da requisição gerado pelo emissor. Esse identificador é ecoado na resposta. Nenhuma verificação dele é feita por parte da paySmart, o emissor é livre para escolher o valor que quiser.  # noqa: E501

        :param issuer_request_id: The issuer_request_id of this NewCreditRequest.
        :type issuer_request_id: str
        """

        self._issuer_request_id = issuer_request_id

    @property
    def inclusion_date(self) -> datetime:
        """Gets the inclusion_date of this NewCreditRequest.

        Data de início de validade/disponibilização de crédito nos cartões.  # noqa: E501

        :return: The inclusion_date of this NewCreditRequest.
        :rtype: datetime
        """
        return self._inclusion_date

    @inclusion_date.setter
    def inclusion_date(self, inclusion_date: datetime):
        """Sets the inclusion_date of this NewCreditRequest.

        Data de início de validade/disponibilização de crédito nos cartões.  # noqa: E501

        :param inclusion_date: The inclusion_date of this NewCreditRequest.
        :type inclusion_date: datetime
        """
        if inclusion_date is None:
            raise ValueError("Invalid value for `inclusion_date`, must not be `None`")  # noqa: E501

        self._inclusion_date = inclusion_date

    @property
    def amount(self) -> AllOfNewCreditRequestAmount:
        """Gets the amount of this NewCreditRequest.

        Valor do crédito a ser adicionado na conta.  # noqa: E501

        :return: The amount of this NewCreditRequest.
        :rtype: AllOfNewCreditRequestAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount: AllOfNewCreditRequestAmount):
        """Sets the amount of this NewCreditRequest.

        Valor do crédito a ser adicionado na conta.  # noqa: E501

        :param amount: The amount of this NewCreditRequest.
        :type amount: AllOfNewCreditRequestAmount
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def credit_type(self) -> int:
        """Gets the credit_type of this NewCreditRequest.

        tipo de caga de crédito realizada (normal, emergencial, etc).  # noqa: E501

        :return: The credit_type of this NewCreditRequest.
        :rtype: int
        """
        return self._credit_type

    @credit_type.setter
    def credit_type(self, credit_type: int):
        """Sets the credit_type of this NewCreditRequest.

        tipo de caga de crédito realizada (normal, emergencial, etc).  # noqa: E501

        :param credit_type: The credit_type of this NewCreditRequest.
        :type credit_type: int
        """
        if credit_type is None:
            raise ValueError("Invalid value for `credit_type`, must not be `None`")  # noqa: E501

        self._credit_type = credit_type

    @property
    def source_audit(self) -> SourceAudit:
        """Gets the source_audit of this NewCreditRequest.


        :return: The source_audit of this NewCreditRequest.
        :rtype: SourceAudit
        """
        return self._source_audit

    @source_audit.setter
    def source_audit(self, source_audit: SourceAudit):
        """Sets the source_audit of this NewCreditRequest.


        :param source_audit: The source_audit of this NewCreditRequest.
        :type source_audit: SourceAudit
        """

        self._source_audit = source_audit
