# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class PinChangeCreatedSuccessfully(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfPinChangeCreatedSuccessfullyResultData=None):  # noqa: E501
        """PinChangeCreatedSuccessfully - a model defined in Swagger

        :param result_data: The result_data of this PinChangeCreatedSuccessfully.  # noqa: E501
        :type result_data: AllOfPinChangeCreatedSuccessfullyResultData
        """
        self.swagger_types = {
            'result_data': AllOfPinChangeCreatedSuccessfullyResultData
        }

        self.attribute_map = {
            'result_data': 'resultData'
        }
        self._result_data = result_data

    @classmethod
    def from_dict(cls, dikt) -> 'PinChangeCreatedSuccessfully':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PinChangeCreatedSuccessfully of this PinChangeCreatedSuccessfully.  # noqa: E501
        :rtype: PinChangeCreatedSuccessfully
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfPinChangeCreatedSuccessfullyResultData:
        """Gets the result_data of this PinChangeCreatedSuccessfully.


        :return: The result_data of this PinChangeCreatedSuccessfully.
        :rtype: AllOfPinChangeCreatedSuccessfullyResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfPinChangeCreatedSuccessfullyResultData):
        """Sets the result_data of this PinChangeCreatedSuccessfully.


        :param result_data: The result_data of this PinChangeCreatedSuccessfully.
        :type result_data: AllOfPinChangeCreatedSuccessfullyResultData
        """

        self._result_data = result_data
