# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SourceAudit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, operator_id: str=None, process_id: str=None):  # noqa: E501
        """SourceAudit - a model defined in Swagger

        :param operator_id: The operator_id of this SourceAudit.  # noqa: E501
        :type operator_id: str
        :param process_id: The process_id of this SourceAudit.  # noqa: E501
        :type process_id: str
        """
        self.swagger_types = {
            'operator_id': str,
            'process_id': str
        }

        self.attribute_map = {
            'operator_id': 'operatorId',
            'process_id': 'processId'
        }
        self._operator_id = operator_id
        self._process_id = process_id

    @classmethod
    def from_dict(cls, dikt) -> 'SourceAudit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SourceAudit of this SourceAudit.  # noqa: E501
        :rtype: SourceAudit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operator_id(self) -> str:
        """Gets the operator_id of this SourceAudit.

        Identificação do operador solicitante. Esta informação é fornecida pelo emissor.  # noqa: E501

        :return: The operator_id of this SourceAudit.
        :rtype: str
        """
        return self._operator_id

    @operator_id.setter
    def operator_id(self, operator_id: str):
        """Sets the operator_id of this SourceAudit.

        Identificação do operador solicitante. Esta informação é fornecida pelo emissor.  # noqa: E501

        :param operator_id: The operator_id of this SourceAudit.
        :type operator_id: str
        """

        self._operator_id = operator_id

    @property
    def process_id(self) -> str:
        """Gets the process_id of this SourceAudit.

        Identificação do processo solicitante. Esta informação é fornecida pelo emissor.  # noqa: E501

        :return: The process_id of this SourceAudit.
        :rtype: str
        """
        return self._process_id

    @process_id.setter
    def process_id(self, process_id: str):
        """Sets the process_id of this SourceAudit.

        Identificação do processo solicitante. Esta informação é fornecida pelo emissor.  # noqa: E501

        :param process_id: The process_id of this SourceAudit.
        :type process_id: str
        """

        self._process_id = process_id
