# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server.models.statement import Statement  # noqa: F401,E501
from swagger_server import util


class StatementList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_data: AllOfStatementListResultData=None, statement_list: List[Statement]=None):  # noqa: E501
        """StatementList - a model defined in Swagger

        :param result_data: The result_data of this StatementList.  # noqa: E501
        :type result_data: AllOfStatementListResultData
        :param statement_list: The statement_list of this StatementList.  # noqa: E501
        :type statement_list: List[Statement]
        """
        self.swagger_types = {
            'result_data': AllOfStatementListResultData,
            'statement_list': List[Statement]
        }

        self.attribute_map = {
            'result_data': 'resultData',
            'statement_list': 'statementList'
        }
        self._result_data = result_data
        self._statement_list = statement_list

    @classmethod
    def from_dict(cls, dikt) -> 'StatementList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatementList of this StatementList.  # noqa: E501
        :rtype: StatementList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_data(self) -> AllOfStatementListResultData:
        """Gets the result_data of this StatementList.


        :return: The result_data of this StatementList.
        :rtype: AllOfStatementListResultData
        """
        return self._result_data

    @result_data.setter
    def result_data(self, result_data: AllOfStatementListResultData):
        """Sets the result_data of this StatementList.


        :param result_data: The result_data of this StatementList.
        :type result_data: AllOfStatementListResultData
        """

        self._result_data = result_data

    @property
    def statement_list(self) -> List[Statement]:
        """Gets the statement_list of this StatementList.

        Lista de faturas.  # noqa: E501

        :return: The statement_list of this StatementList.
        :rtype: List[Statement]
        """
        return self._statement_list

    @statement_list.setter
    def statement_list(self, statement_list: List[Statement]):
        """Sets the statement_list of this StatementList.

        Lista de faturas.  # noqa: E501

        :param statement_list: The statement_list of this StatementList.
        :type statement_list: List[Statement]
        """

        self._statement_list = statement_list
