# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SALE = "sale"
    WITHDRAWAL = "withdrawal"
    DEBIT_ADJUSTMENT = "debit_adjustment"
    UNDOING_LOAD_CREDIT = "undoing_load_credit"
    LOADING_CREDIT = "loading_credit"
    CREDIT_ADJUSTMENT = "credit_adjustment"
    SALE_CHARGEBACK = "sale_chargeback"
    def __init__(self):  # noqa: E501
        """TransactionType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionType of this TransactionType.  # noqa: E501
        :rtype: TransactionType
        """
        return util.deserialize_model(dikt, cls)
