# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transaction_id: str=None):  # noqa: E501
        """TransactionId - a model defined in Swagger

        :param transaction_id: The transaction_id of this TransactionId.  # noqa: E501
        :type transaction_id: str
        """
        self.swagger_types = {
            'transaction_id': str
        }

        self.attribute_map = {
            'transaction_id': 'transaction_id'
        }
        self._transaction_id = transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionId of this TransactionId.  # noqa: E501
        :rtype: TransactionId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_id(self) -> str:
        """Gets the transaction_id of this TransactionId.


        :return: The transaction_id of this TransactionId.
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: str):
        """Sets the transaction_id of this TransactionId.


        :param transaction_id: The transaction_id of this TransactionId.
        :type transaction_id: str
        """

        self._transaction_id = transaction_id
