# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.credit_info import CreditInfo  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server.models.source_audit import SourceAudit  # noqa: F401,E501
from swagger_server import util


class UpdateAccountRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, issuer_request_id: str=None, credit_info: CreditInfo=None, billing_address: AllOfUpdateAccountRequestBillingAddress=None, card_delivery_address: AllOfUpdateAccountRequestCardDeliveryAddress=None, source_audit: SourceAudit=None):  # noqa: E501
        """UpdateAccountRequest - a model defined in Swagger

        :param issuer_request_id: The issuer_request_id of this UpdateAccountRequest.  # noqa: E501
        :type issuer_request_id: str
        :param credit_info: The credit_info of this UpdateAccountRequest.  # noqa: E501
        :type credit_info: CreditInfo
        :param billing_address: The billing_address of this UpdateAccountRequest.  # noqa: E501
        :type billing_address: AllOfUpdateAccountRequestBillingAddress
        :param card_delivery_address: The card_delivery_address of this UpdateAccountRequest.  # noqa: E501
        :type card_delivery_address: AllOfUpdateAccountRequestCardDeliveryAddress
        :param source_audit: The source_audit of this UpdateAccountRequest.  # noqa: E501
        :type source_audit: SourceAudit
        """
        self.swagger_types = {
            'issuer_request_id': str,
            'credit_info': CreditInfo,
            'billing_address': AllOfUpdateAccountRequestBillingAddress,
            'card_delivery_address': AllOfUpdateAccountRequestCardDeliveryAddress,
            'source_audit': SourceAudit
        }

        self.attribute_map = {
            'issuer_request_id': 'issuerRequestId',
            'credit_info': 'creditInfo',
            'billing_address': 'billingAddress',
            'card_delivery_address': 'cardDeliveryAddress',
            'source_audit': 'sourceAudit'
        }
        self._issuer_request_id = issuer_request_id
        self._credit_info = credit_info
        self._billing_address = billing_address
        self._card_delivery_address = card_delivery_address
        self._source_audit = source_audit

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateAccountRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateAccountRequest of this UpdateAccountRequest.  # noqa: E501
        :rtype: UpdateAccountRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issuer_request_id(self) -> str:
        """Gets the issuer_request_id of this UpdateAccountRequest.

        Identificador único da requisição gerado pelo emissor. Esse identificador é ecoado na resposta. Nenhuma verificação dele é feita por parte da paySmart, o emissor é livre para escolher o valor que quiser.  # noqa: E501

        :return: The issuer_request_id of this UpdateAccountRequest.
        :rtype: str
        """
        return self._issuer_request_id

    @issuer_request_id.setter
    def issuer_request_id(self, issuer_request_id: str):
        """Sets the issuer_request_id of this UpdateAccountRequest.

        Identificador único da requisição gerado pelo emissor. Esse identificador é ecoado na resposta. Nenhuma verificação dele é feita por parte da paySmart, o emissor é livre para escolher o valor que quiser.  # noqa: E501

        :param issuer_request_id: The issuer_request_id of this UpdateAccountRequest.
        :type issuer_request_id: str
        """

        self._issuer_request_id = issuer_request_id

    @property
    def credit_info(self) -> CreditInfo:
        """Gets the credit_info of this UpdateAccountRequest.


        :return: The credit_info of this UpdateAccountRequest.
        :rtype: CreditInfo
        """
        return self._credit_info

    @credit_info.setter
    def credit_info(self, credit_info: CreditInfo):
        """Sets the credit_info of this UpdateAccountRequest.


        :param credit_info: The credit_info of this UpdateAccountRequest.
        :type credit_info: CreditInfo
        """

        self._credit_info = credit_info

    @property
    def billing_address(self) -> AllOfUpdateAccountRequestBillingAddress:
        """Gets the billing_address of this UpdateAccountRequest.

        Endereço de faturamento da conta.  # noqa: E501

        :return: The billing_address of this UpdateAccountRequest.
        :rtype: AllOfUpdateAccountRequestBillingAddress
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address: AllOfUpdateAccountRequestBillingAddress):
        """Sets the billing_address of this UpdateAccountRequest.

        Endereço de faturamento da conta.  # noqa: E501

        :param billing_address: The billing_address of this UpdateAccountRequest.
        :type billing_address: AllOfUpdateAccountRequestBillingAddress
        """

        self._billing_address = billing_address

    @property
    def card_delivery_address(self) -> AllOfUpdateAccountRequestCardDeliveryAddress:
        """Gets the card_delivery_address of this UpdateAccountRequest.

        Endereço para entrega do cartão.  # noqa: E501

        :return: The card_delivery_address of this UpdateAccountRequest.
        :rtype: AllOfUpdateAccountRequestCardDeliveryAddress
        """
        return self._card_delivery_address

    @card_delivery_address.setter
    def card_delivery_address(self, card_delivery_address: AllOfUpdateAccountRequestCardDeliveryAddress):
        """Sets the card_delivery_address of this UpdateAccountRequest.

        Endereço para entrega do cartão.  # noqa: E501

        :param card_delivery_address: The card_delivery_address of this UpdateAccountRequest.
        :type card_delivery_address: AllOfUpdateAccountRequestCardDeliveryAddress
        """

        self._card_delivery_address = card_delivery_address

    @property
    def source_audit(self) -> SourceAudit:
        """Gets the source_audit of this UpdateAccountRequest.


        :return: The source_audit of this UpdateAccountRequest.
        :rtype: SourceAudit
        """
        return self._source_audit

    @source_audit.setter
    def source_audit(self, source_audit: SourceAudit):
        """Sets the source_audit of this UpdateAccountRequest.


        :param source_audit: The source_audit of this UpdateAccountRequest.
        :type source_audit: SourceAudit
        """

        self._source_audit = source_audit
